{
//=========Macro generated from canvas: cnv/cnv
//=========  (Mon Mar 16 14:07:34 2015) by ROOT version5.34/18
   TCanvas *cnv = new TCanvas("cnv", "cnv",1320,22,904,928);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cnv->SetHighLightColor(2);
   cnv->Range(-2.125,-1.151148,10.375,7.703838);
   cnv->SetFillColor(0);
   cnv->SetBorderMode(0);
   cnv->SetBorderSize(2);
   cnv->SetTickx(1);
   cnv->SetTicky(1);
   cnv->SetLeftMargin(0.17);
   cnv->SetRightMargin(0.03);
   cnv->SetTopMargin(0.07);
   cnv->SetBottomMargin(0.13);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   
   TH1F *h_gammaD_cT_dummy = new TH1F("h_gammaD_cT_dummy","h_gammaD_cT_dummy",100,0,10);
   h_gammaD_cT_dummy->SetMaximum(7.083989);
   h_gammaD_cT_dummy->SetLineStyle(0);
   h_gammaD_cT_dummy->SetMarkerStyle(20);
   h_gammaD_cT_dummy->GetXaxis()->SetTitle("c#tau of #gamma_{D} [mm]");
   h_gammaD_cT_dummy->GetXaxis()->SetLabelFont(42);
   h_gammaD_cT_dummy->GetXaxis()->SetLabelOffset(0.007);
   h_gammaD_cT_dummy->GetXaxis()->SetTitleSize(0.06);
   h_gammaD_cT_dummy->GetXaxis()->SetTitleOffset(0.95);
   h_gammaD_cT_dummy->GetXaxis()->SetTitleFont(42);
   h_gammaD_cT_dummy->GetYaxis()->SetTitle("Normalized Fraction of Events / 0.1 mm");
   h_gammaD_cT_dummy->GetYaxis()->SetLabelFont(42);
   h_gammaD_cT_dummy->GetYaxis()->SetLabelOffset(0.007);
   h_gammaD_cT_dummy->GetYaxis()->SetTitleSize(0.05);
   h_gammaD_cT_dummy->GetYaxis()->SetTitleOffset(1.3);
   h_gammaD_cT_dummy->GetYaxis()->SetTitleFont(42);
   h_gammaD_cT_dummy->GetZaxis()->SetLabelFont(42);
   h_gammaD_cT_dummy->GetZaxis()->SetLabelOffset(0.007);
   h_gammaD_cT_dummy->GetZaxis()->SetTitleSize(0.06);
   h_gammaD_cT_dummy->GetZaxis()->SetTitleFont(42);
   h_gammaD_cT_dummy->Draw("");
   
   TH1F *h_gammaD_cT = new TH1F("h_gammaD_cT","h_gammaD_cT",100,0,10);
   h_gammaD_cT->SetBinContent(1,3.935549);
   h_gammaD_cT->SetBinContent(2,2.383655);
   h_gammaD_cT->SetBinContent(3,1.459331);
   h_gammaD_cT->SetBinContent(4,0.8693234);
   h_gammaD_cT->SetBinContent(5,0.5290066);
   h_gammaD_cT->SetBinContent(6,0.3229415);
   h_gammaD_cT->SetBinContent(7,0.1953149);
   h_gammaD_cT->SetBinContent(8,0.119564);
   h_gammaD_cT->SetBinContent(9,0.0723759);
   h_gammaD_cT->SetBinContent(10,0.04743809);
   h_gammaD_cT->SetBinContent(11,0.0242503);
   h_gammaD_cT->SetBinContent(12,0.0161252);
   h_gammaD_cT->SetBinContent(13,0.01093764);
   h_gammaD_cT->SetBinContent(14,0.005500069);
   h_gammaD_cT->SetBinContent(15,0.003750047);
   h_gammaD_cT->SetBinContent(16,0.002500031);
   h_gammaD_cT->SetBinContent(17,0.0008125101);
   h_gammaD_cT->SetBinContent(18,0.0006875086);
   h_gammaD_cT->SetBinContent(19,0.0004375055);
   h_gammaD_cT->SetBinContent(20,0.0002500031);
   h_gammaD_cT->SetBinContent(21,0.0001250016);
   h_gammaD_cT->SetBinContent(24,6.250078e-05);
   h_gammaD_cT->SetBinContent(26,6.250078e-05);
   h_gammaD_cT->SetEntries(159998);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#0000ff");
   h_gammaD_cT->SetLineColor(ci);
   h_gammaD_cT->SetLineWidth(2);
   h_gammaD_cT->SetMarkerStyle(20);
   h_gammaD_cT->GetXaxis()->SetTitle("c#tau of #gamma_{D} [mm]");
   h_gammaD_cT->GetXaxis()->SetLabelFont(42);
   h_gammaD_cT->GetXaxis()->SetLabelOffset(0.007);
   h_gammaD_cT->GetXaxis()->SetTitleSize(0.06);
   h_gammaD_cT->GetXaxis()->SetTitleOffset(0.95);
   h_gammaD_cT->GetXaxis()->SetTitleFont(42);
   h_gammaD_cT->GetYaxis()->SetTitle("Normalized Fraction of events");
   h_gammaD_cT->GetYaxis()->SetLabelFont(42);
   h_gammaD_cT->GetYaxis()->SetLabelOffset(0.007);
   h_gammaD_cT->GetYaxis()->SetTitleSize(0.05);
   h_gammaD_cT->GetYaxis()->SetTitleOffset(1.5);
   h_gammaD_cT->GetYaxis()->SetTitleFont(42);
   h_gammaD_cT->GetZaxis()->SetLabelFont(42);
   h_gammaD_cT->GetZaxis()->SetLabelOffset(0.007);
   h_gammaD_cT->GetZaxis()->SetTitleSize(0.06);
   h_gammaD_cT->GetZaxis()->SetTitleFont(42);
   h_gammaD_cT->Draw("same");
   
   TF1 *funct = new TF1("funct","exp(-x/0.00)/(0.00*(1-exp(-10/0.00)))",0,10);
   funct->SetNpx(10000);
   funct->SetFillColor(19);
   funct->SetFillStyle(0);
   funct->SetMarkerStyle(20);
   funct->SetLineColor(2);
   funct->SetLineWidth(1);
   funct->GetXaxis()->SetLabelFont(42);
   funct->GetXaxis()->SetLabelOffset(0.007);
   funct->GetXaxis()->SetTitleSize(0.06);
   funct->GetXaxis()->SetTitleOffset(0.95);
   funct->GetXaxis()->SetTitleFont(42);
   funct->GetYaxis()->SetLabelFont(42);
   funct->GetYaxis()->SetLabelOffset(0.007);
   funct->GetYaxis()->SetTitleSize(0.06);
   funct->GetYaxis()->SetTitleOffset(1.3);
   funct->GetYaxis()->SetTitleFont(42);
   funct->Draw("same");
   
   TLegend *leg = new TLegend(0.4566667,0.82,0.7822222,0.9066667,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.02777778);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","#splitline{pp #rightarrow h #rightarrow 2n_{1} #rightarrow 2n_{D} + 2 #gamma_{D} #rightarrow 2n_{D} + 4#mu}{#splitline{m_{h} = 125_mGammaD_03 GeV, m_{n_{1}} = 10 GeV, m_{n_{D}} = 1 GeV}{m_{#gamma_{D}} = 0300_ctauExp.300_ctauExp_02_8 GeV, c#tau_{#gamma_{D}} = 0.00 mm}}","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.17,0.935,0.97,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(22);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("NULL","CMS Simulation (LHE) ctauExp_02_8 TeV","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.46,0.6744444,0.6955556,0.7644444,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.02777778);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("funct","#frac{e^{-x/0.00}}{0.00 (1 - e^{-10/0.00})}","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   cnv->Modified();
   cnv->cd();
   cnv->SetSelected(cnv);
}
